[SQUASH] Fix standalone compilation
video: msm: mdss: Fix trace include path

Signed-off-by: Michal Chvíla <electrydev@gmail.com>

sound: soc: msm: Fix in-tree compilation

In-tree compilation for sound/soc/msm/qdsp6v2/rtac.c was hitting
this error:

sound/soc/msm/qdsp6v2/rtac.c:29:21: fatal error: q6voice.h: No such
file or directory
 #include <q6voice.h>

This was due to using <> instead of "" style include.

Signed-off-by: Michal Chvíla <electrydev@gmail.com>

msm: smd: Fix in-tree compilation

In-tree compilation for arch/arm/mach-msm/smd_init_dt.c was hitting this
error:

arch/arm/mach-msm/smd_init_dt.c:24:25: fatal error: smd_private.h: No such
file or directory
 #include <smd_private.h>

This was due to using <> instead of "" style include.

Signed-off-by: Michal Chvíla <electrydev@gmail.com>